services:
  gwn-mqtt-bridge:
    image: ghcr.io/shopsD/homeassistant-grandstream-gwn:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gwn-mqtt-bridge
    restart: unless-stopped

    volumes:
      - ./config:/config

    environment:
      PYTHONUNBUFFERED: "1"
