from dataclasses import dataclass
from typing import ClassVar

import meta_data.project_meta

@dataclass(slots=True)
class Constants:
    LOG:ClassVar[str] = "gwn_mqtt"
    APP_VERSION:ClassVar[str] = meta_data.project_meta.APP_VERSION

    # mqtt keys
    # ssid
    SSID_NAME: ClassVar[str] = "ssidName"
    WIFI_ENABLED: ClassVar[str] = "wifiEnabled"
    CLIENT_COUNT: ClassVar[str] = "onlineDevices"
    SCHEDULE_ENABLED: ClassVar[str] = "scheduleEnabled"
    PORTAL_ENABLED: ClassVar[str] = "portalEnabled"
    MAC_FILTERING_ENABLED: ClassVar[str] = "macFilteringEnabled"
    CLIENT_ISOLATION_ENABLED: ClassVar[str] = "clientIsolationEnabled"
    SSID_ISOLATION_MODE: ClassVar[str] = "ssidIsolationMode"
    SSID_ISOLATION: ClassVar[str] = "ssidIsolation"
    SSID_HIDDEN: ClassVar[str] = "ssidSsidHidden"
    SSID_VLAN_ID: ClassVar[str] = "ssidVlanid"
    SSID_VLAN_ENABLED: ClassVar[str] = "ssidVlanEnabled"
    SSID_ENABLE: ClassVar[str] = "ssidEnable"
    SSID_REMARK: ClassVar[str] = "ssidRemark"
    SSID_KEY: ClassVar[str] = "ssidKey"
    GHZ2_4_ENABLED: ClassVar[str] = "ghz2_4_Enabled"
    GHZ5_ENABLED: ClassVar[str] = "ghz5_Enabled"
    GHZ6_ENABLED: ClassVar[str] = "ghz6_Enabled"
    ASSIGNED_DEVICES: ClassVar[str] = "assignedDevices"

    # device
    STATUS: ClassVar[str] = "status"
    AP_TYPE: ClassVar[str] = "apType"
    MAC: ClassVar[str] = "mac"
    NAME: ClassVar[str] = "name"
    IPV4: ClassVar[str] = "ip"
    UP_TIME: ClassVar[str] = "upTime"
    USAGE: ClassVar[str] = "usage"
    UPLOAD: ClassVar[str] = "upload"
    DOWNLOAD: ClassVar[str] = "download"
    CLIENTS: ClassVar[str] = "clients"
    CURRENT_FIRMWARE: ClassVar[str] = "versionFirmware"
    IPV6: ClassVar[str] = "ipv6"
    NEW_FIRMWARE: ClassVar[str] = "newFirmware"
    WIRELESS: ClassVar[str] = "wireless"
    VLAN_MAX_SIZE: ClassVar[str] = "vlanCount"
    SSID_COUNT: ClassVar[str] = "ssidNumber"
    ONLINE_STATUS: ClassVar[str] = "online"
    MODEL: ClassVar[str] = "model"
    DEVICE_TYPE: ClassVar[str] = "deviceType"
    CHANNEL_5: ClassVar[str] = "channel_5"
    CHANNEL_2_4: ClassVar[str] = "channel_2_4"
    CHANNEL_6: ClassVar[str] = "channel_6"
    PART_NUMBER: ClassVar[str] = "partNumber"
    BOOT_VERSION: ClassVar[str] = "bootVersion"
    NETWORK: ClassVar[str] = "network"
    TEMPERATURE: ClassVar[str] = "temperature"
    USED_MEMORY: ClassVar[str] = "usedMemory"
    CHANNEL_LOAD_2G4: ClassVar[str] = "channelload_2g4"
    CHANNEL_LOAD_6G: ClassVar[str] = "channelload_6g"
    CPU_USAGE: ClassVar[str] = "cpuUsage"
    CHANNEL_LOAD_5G: ClassVar[str] = "channelload_5g"
    AP_2G4_CHANNEL: ClassVar[str] = "ap_2g4_channel"
    AP_5G_CHANNEL: ClassVar[str] = "ap_5g_channel"
    AP_6G_CHANNEL: ClassVar[str] = "ap_6g_channel" # potentially unsupported
    # NETWORK_NAME (In Network)
    SSIDS: ClassVar[str] = "ssids"
    # Used for selection
    CHANNEL_LISTS_2G4: ClassVar[str] = "channel_lists_2g4"
    CHANNEL_LISTS_5G: ClassVar[str] = "channel_lists_5g"
    CHANNEL_LISTS_6G: ClassVar[str] = "channel_lists_6g"

    # buttons/commands (no GWN Inputs)
    REBOOT: ClassVar[str] = "reboot"
    UPDATE_FIRMWARE: ClassVar[str] = "update_firmware"
    RESET: ClassVar[str] = "reset"

    # network
    COUNTRY_DISPLAY: ClassVar[str] = "countryDisplay"
    TIMEZONE: ClassVar[str] = "timezone"
    NETWORK_NAME: ClassVar[str] = "networkName"

    # application 
    CURRENT_VERSION: ClassVar[str] = "currentVersion"
    NEW_VERSION: ClassVar[str] = "newVersion"
    UPDATE_VERSION: ClassVar[str] = "update_version"
    RESTART: ClassVar[str] = "restart"

    # mqtt command envelope
    ACTION: ClassVar[str] = "action"
    VALUE: ClassVar[str] = "value"
    ACTIONS: ClassVar[str] = "actions"
    NETWORK_ID: ClassVar[str] = "network_id"
    SSID_ID: ClassVar[str] = "ssid_id"
    TOGGLE_DEVICE: ClassVar[str] = "toggle_device"
    DEVICE_MACS: ClassVar[str] = "device_macs"

    # Non-Discovery SSID Payload Inputs
    SSID_RADIUS_DYNAMIC_VLAN: ClassVar[str] = "ssidRadiusDynamicVlan"
    SSID_NEW_SSID_BAND: ClassVar[str] = "ssidNewSsidBand"
    SSID_WIFI_CLIENT_LIMIT: ClassVar[str] = "ssidWifiClientLimit"
    SSID_ENCRYPTION: ClassVar[str] = "ssidEncryption"
    SSID_WEP_KEY: ClassVar[str] = "ssidWepKey"
    SSID_WPA_KEY_MODE: ClassVar[str] = "ssidWpaKeyMode"
    SSID_WPA_ENCRYPTION: ClassVar[str] = "ssidWpaEncryption"
    SSID_WPA_KEY: ClassVar[str] = "ssidWpaKey"
    SSID_BRIDGE_ENABLE: ClassVar[str] = "ssidBridgeEnable"
    SSID_GATEWAY_MAC: ClassVar[str] = "ssidGatewayMac"
    SSID_VOICE_ENTERPRISE: ClassVar[str] = "ssidVoiceEnterprise"
    SSID_11V: ClassVar[str] = "ssid11V"
    SSID_11R: ClassVar[str] = "ssid11R"
    SSID_11K: ClassVar[str] = "ssid11K"
    SSID_DTIM_PERIOD: ClassVar[str] = "ssidDtimPeriod"
    SSID_MCAST_TO_UCAST: ClassVar[str] = "ssidMcastToUcast"
    SSID_PROXYARP: ClassVar[str] = "ssidProxyarp"
    SSID_STA_IDLE_TIMEOUT: ClassVar[str] = "ssidStaIdleTimeout"
    SSID_11W: ClassVar[str] = "ssid11W"
    SSID_BMS: ClassVar[str] = "ssidBms"
    SSID_CLIENT_IP_ASSIGNMENT: ClassVar[str] = "ssidClientIPAssignment"
    BIND_MACS: ClassVar[str] = "bindMacs"
    REMOVE_MACS: ClassVar[str] = "removeMacs"
    SSID_PORTAL_POLICY: ClassVar[str] = "ssidPortalPolicy"
    SSID_MACLIST_BLACKS: ClassVar[str] = "ssidMaclistBlacks"
    SSID_MACLIST_WHITES: ClassVar[str] = "ssidMaclistWhites"
    SSID_MAC_FILTERING: ClassVar[str] = "ssidMacFiltering"
    SCHEDULE_ID: ClassVar[str] = "scheduleId"
    SSID_TIMED_CLIENT_POLICY: ClassVar[str] = "ssidTimedClientPolicy"
    BANDWIDTH_TYPE: ClassVar[str] = "bandwidthType"
    BANDWIDTH_RULES: ClassVar[str] = "bandwidthRules"
    SSID_SECURITY_TYPE: ClassVar[str] = "ssidSecurityType"
    PPSK_PROFILE: ClassVar[str] = "ppskProfile"
    RADIUS_PROFILE: ClassVar[str] = "radiusProfile"

    # Non-Discovery Device Payload Inputs
    AP_2G4_POWER: ClassVar[str] = "ap_2g4_power"
    AP_2G4_RATELIMIT_ENABLE: ClassVar[str] = "ap_2g4_ratelimit_enable"
    AP_2G4_RSSI: ClassVar[str] = "ap_2g4_rssi"
    AP_2G4_RSSI_ENABLE: ClassVar[str] = "ap_2g4_rssi_enable"
    AP_2G4_TAG: ClassVar[str] = "ap_2g4_tag"
    AP_2G4_WIDTH: ClassVar[str] = "ap_2g4_width"
    AP_5G_POWER: ClassVar[str] = "ap_5g_power"
    AP_5G_RATELIMIT_ENABLE: ClassVar[str] = "ap_5g_ratelimit_enable"
    AP_5G_RSSI: ClassVar[str] = "ap_5g_rssi"
    AP_5G_RSSI_ENABLE: ClassVar[str] = "ap_5g_rssi_enable"
    AP_5G_TAG: ClassVar[str] = "ap_5g_tag"
    AP_5G_WIDTH: ClassVar[str] = "ap_5g_width"
    AP_ALTERNATE_DNS: ClassVar[str] = "ap_alternate_dns"
    AP_BAND_STEERING: ClassVar[str] = "ap_band_steering"
    AP_IPV4_ROUTE: ClassVar[str] = "ap_ipv4_route"
    AP_IPV4_STATIC: ClassVar[str] = "ap_ipv4_static"
    AP_IPV4_STATIC_MASK: ClassVar[str] = "ap_ipv4_static_mask"
    AP_NAME: ClassVar[str] = "ap_name"
    AP_PREFERRED_DNS: ClassVar[str] = "ap_preferred_dns"
    AP_STATIC: ClassVar[str] = "ap_static"
    AP_6G_POWER: ClassVar[str] = "ap_6g_power"
    AP_6G_RATELIMIT_ENABLE: ClassVar[str] = "ap_6g_ratelimit_enable"
    AP_6G_RSSI: ClassVar[str] = "ap_6g_rssi"
    AP_6G_RSSI_ENABLE: ClassVar[str] = "ap_6g_rssi_enable"
    AP_6G_TAG: ClassVar[str] = "ap_6g_tag"
    AP_6G_WIDTH: ClassVar[str] = "ap_6g_width"

    # Non-Discovery Network Payload Inputs
    COUNTRY: ClassVar[str] = "country"
    NETWORK_ADMINS: ClassVar[str] = "networkAdministrators"

    # MQTT Topics
    APPLICATION: ClassVar[str] = "application"
    DEVICES: ClassVar[str] = "devices"
    GWN: ClassVar[str] = "gwn"
    NETWORKS: ClassVar[str] = "networks"
    SET: ClassVar[str] = "set"
    STATE: ClassVar[str] = "state"
    CONFIG: ClassVar[str] = "config"

    # Application Processing
    CACHE: ClassVar[str] = "cache"
